---
title: "BSD decay?"
output: github_document
---

```{r setup}
library(isds)
library(ggplot2)
library(dplyr)
library(tidyr)
knitr::opts_chunk$set(echo = TRUE)

toyp <- get_toy_portal_data(years = 1990:2010)
```

```{r get bsds}
ebsd <- toyp %>%
  group_by(species) %>%
  summarize(meanwgt = mean(wgt)) %>%
  ungroup() %>%
  mutate(logwgt = log(meanwgt))

set.seed(1977)

nsims = 1

uniform_log_bsd <- replicate(n = nsims, expr = draw_uniform_bsd(s = nrow(ebsd), min =  min(ebsd$meanwgt), max =max(ebsd$meanwgt)))

uniform_log_bsd <- as.data.frame(uniform_log_bsd) %>%
  tidyr::gather(key = "sim", value = "val") %>%
  dplyr::mutate(sim = as.integer(substr(sim, start = 2, stop = nchar(sim))),
                source = "uniform")

unimodal_log_bsd <- replicate(n = nsims, expr = draw_unimodal_bsd(ebsd$meanwgt))
unimodal_log_bsd <- as.data.frame(unimodal_log_bsd) %>%
  tidyr::gather(key = "sim", value = "val") %>%
  dplyr::mutate(sim = as.integer(substr(sim, start = 2, stop = nchar(sim))),
                source = "unimodal")

mmodal_log_bsd_full <- replicate(n = nsims, expr = draw_multimodal_bsd(emp_vector = ebsd$meanwgt, min_mode_gap_coeff = 1.5, min_sd_coeff = .2, max_sd_coeff = .2), simplify = F)

mmodal_log_bsd <- lapply(mmodal_log_bsd_full, FUN = function(X) return(X$bsd))
mmodal_log_bsd <- dplyr::bind_cols(mmodal_log_bsd) %>%
   tidyr::gather(key = "sim", value = "val") %>%
  dplyr::mutate(sim = as.integer(substr(sim, start = 2, stop = nchar(sim))),
                source = "mmodal")

empirical_log_bsd <- ebsd %>%
  select(meanwgt) %>%
  mutate(sim = -99, source = "empirical") %>%
  rename(val = meanwgt)

all_bsds <- bind_rows(empirical_log_bsd, mmodal_log_bsd, uniform_log_bsd, unimodal_log_bsd)


```

```{r get nb modes}
bsd_modes <- all_bsds %>%
  group_by(source, sim) %>%
  summarize(nb_modes = get_n_clumps(val),
            nb_modes_bic = Mclust(val, G = c(1:5))$G) %>%
  ungroup()

```
```{r plot nb modes}

modes_plot <- ggplot(data = bsd_modes, aes(x = nb_modes, color = source, fill = source)) +
  geom_histogram() +
  geom_point(data = bsd_modes[ which(bsd_modes$source == "empirical"), ], aes (x = nb_modes, y = nsims / 4), shape = 8, size = 3) + 
  facet_grid(source ~ . ) +
  theme_bw()


modes_plot

```


```{r single bsd plots}

single_bsds <- lapply(unique(all_bsds$source), FUN = function(X)  return(filter(all_bsds, sim == sample.int(n = nsims, size = 1), source == X)))

single_bsds <- bind_rows(single_bsds) %>%
  left_join(bsd_modes, by = c("sim", "source")) %>%
  mutate(facet_name = paste0("source: ", source, "; ", nb_modes, " mode(s); ", nb_modes_bic, " mode(s) w BIC"))

single_bsd_density_plots <- ggplot(data = single_bsds, aes(x = val, color = source)) +
  geom_density() + 
  facet_wrap(facet_name ~ .) +
  theme_bw()

single_bsd_density_plots

single_bsd_histograms <- ggplot(data = single_bsds, aes(x = val, fill = source, color = source)) +
  geom_histogram() + 
  facet_wrap(facet_name ~ .) +
  theme_bw()

single_bsd_histograms

empirical_density_plot <- ggplot(data = filter(all_bsds, source == "empirical"), aes (x = val)) +
  geom_density() +
  ggtitle(paste0("Empirical BSD: ", filter(bsd_modes, source == "empirical")$nb_modes, " mode(s)")) +
  theme_bw()

empirical_count_plot <-  ggplot(data = filter(all_bsds, source == "empirical"), aes (x = val)) +
  geom_histogram() +
  ggtitle(paste0("Empirical BSD: ", filter(bsd_modes, source == "empirical")$nb_modes, " mode(s)")) +
  theme_bw()

gridExtra::grid.arrange(grobs = list(empirical_density_plot, empirical_count_plot), nrow = 1)


print(filter(bsd_modes, source == "empirical"))
```
