---
title: "New workflow"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warnings = FALSE, error = FALSE)
library(dplyr)
library(isds)
library(ggplot2)
source(here::here("analysis", "fxns.R"))
```

```{r load isd}

portal <- get_toy_portal_data(years = c(1980:1985), download = F)

head(portal)

portal <- suppressWarnings(get_clumps(portal, max_n_clumps = length(unique(portal[,1]))) %>%
  mutate(source = "empirical",
         clump = as.factor(clump)))

nsims = 20
```

```{r sims}
uniform_clumps <- suppressWarnings(replicate(nsims, sim_wrapper(portal, "uniform"), simplify = F))
names(uniform_clumps) <- 1:nsims

c_clumps <- suppressWarnings(replicate(nsims, sim_wrapper(portal, "constrained"), simplify = F))
names(c_clumps) <- 1:nsims

c_d_clumps <- suppressWarnings(replicate(nsims, sim_wrapper(portal, "constrained_density"), simplify = F))
names(c_d_clumps) <- 1:nsims

```

```{r plot, fig.width = 50, fig.height = 50}

all_sim_clumps <- bind_rows(
  list(uniform = bind_rows(uniform_clumps, .id = "sim"), 
  constrained = bind_rows(c_clumps, .id = "sim"), 
  constrained_density = bind_rows(c_d_clumps, .id = "sim")), .id = "source") %>%
  mutate(clump = as.factor(clump))

empirical_plot <- ggplot(data = portal, aes(x = wgt, fill = clump, group = clump)) +
   geom_histogram(binwidth = 1) +
  scale_fill_viridis_d(end = .8) +
  theme_bw()

clump_plot <- ggplot(data = all_sim_clumps, aes(x = wgt, fill = source, group = clump)) +
  geom_histogram(binwidth = 1) +
  facet_wrap(vars(source, sim)) +
  scale_fill_viridis_d(end = .8) +
  theme_bw()


clump_plot

```
```{r emp}
empirical_plot
```

```{r summarize sims}

sim_clump_summary <- summarize_clumps(all_sim_clumps)
emp_clump_summary <- summarize_clumps(portal)


nclumps_summary_plot <- ggplot(data = sim_clump_summary, aes(x = nclumps, fill = source, group = source)) +
  geom_histogram(binwidth = 1) +
  theme_bw() +
  geom_vline(xintercept = emp_clump_summary$nclumps[1]) +
  facet_wrap(vars(source), ncol = 1) +
  xlim(-1, max(sim_clump_summary$nclumps) + 2) +
  scale_fill_viridis_d(end = .8) +
  theme(legend.position = "none")


indwidth_summary_plot <- ggplot(data = sim_clump_summary, aes(x = mean_ind_width, fill = source, group = source)) +
  geom_histogram() +
  theme_bw() +
  geom_vline(xintercept = emp_clump_summary$mean_ind_width[1]) +
  facet_wrap(vars(source), ncol = 1) +
  scale_fill_viridis_d(end = .8) +
  theme(legend.position = "none")

gridExtra::grid.arrange(grobs = list(nclumps_summary_plot, indwidth_summary_plot), ncol = 2)

```
