---
title: "No thresholds"
output: html_notebook
---

```{r setup}
library(drake)
library(isds)
library(ggplot2)
## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("drake", "drake-cache.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
```

```{r load things}

all_ids <- cached(cache = cache) [ which(substr(cached(cache = cache), 0, 2) == "id")]
all_ids <- all_ids[ which(grepl("dat1", all_ids))]
all_ids <- all_ids[ which(!grepl("plot", all_ids))]


# for(i in 1:length(all_ids)) {
# loadd(all_ids[i], cache = cache, character_only = T)
# }

ids <- lapply(all_ids, readd, cache = cache, character_only  = T)
```

```{r get stats}

get_result_not <- function(integrated_density) {
  result <- data.frame(npeaks = count_peaks(integrated_density),
                       dat_type = get_type(integrated_density),
                       datname = get_datname(integrated_density),
                       stdev = get_stdev(integrated_density),
                       ratio_mean = get_mode_ratio(integrated_density, what = "mean"),
                       ratio_sd = get_mode_ratio(integrated_density, what = "stdev"),
                       scaled_e_change = get_scaled_e_change(integrated_density),
                       mean_p = get_mean_p(integrated_density)
  )
  
  result$dat_type <- as.character(result$dat_type)
  
  return(result)
}

# for(i in 1:length(ids)) {
#   get_result_not(ids[[i]])
# }

result <- lapply(ids, get_result_not)
result <- dplyr::bind_rows(result)
```

Plots for
- nmodes (!)
- mean ratio
- sdev of ratio
- elevation change
- mean p

wrapped by standard deviation


```{r empirical v sim plots}
nmodes_plot <- ggplot(data = result[ which(result$dat_type == "sim"), ], aes(x = npeaks)) +
  geom_histogram(bins = 10) +
  geom_vline(xintercept = result[ which(result$dat_type == "emp"), "npeaks"], color = "red") + 
  facet_wrap(stdev ~ .) +
  ggtitle("Number of modes") +
  theme_bw()
nmodes_plot

mr_plot <- ggplot(data = result[ which(result$dat_type == "sim"), ], aes(x = ratio_mean)) +
  geom_histogram(bins = 10) +
  geom_vline(xintercept = result[ which(result$dat_type == "emp"), "ratio_mean"], color = "red") + 
  facet_wrap(stdev ~ .) +
  ggtitle("Mean ratio of modes") +
  theme_bw()
mr_plot

stdr_plot <- ggplot(data = result[ which(result$dat_type == "sim"), ], aes(x = ratio_sd)) +
  geom_histogram(bins = 10) +
  geom_vline(xintercept = result[ which(result$dat_type == "emp"), "ratio_sd"], color = "red") + 
    facet_wrap(stdev ~ .) +
  ggtitle("Mean standard deviation of modes") +
  theme_bw()
stdr_plot

echange_plot <- ggplot(data = result[ which(result$dat_type == "sim"), ], aes(x = scaled_e_change)) +
  geom_histogram(bins = 10) +
  geom_vline(xintercept = result[ which(result$dat_type == "emp"), "scaled_e_change"], color = "red") + 
  facet_wrap(stdev ~ .) +
  ggtitle("Scaled elevation change") +
  theme_bw()
echange_plot


meanp_plot <- ggplot(data = result[ which(result$dat_type == "sim"), ], aes(x = mean_p)) +
  geom_histogram(bins = 10) +
  geom_vline(xintercept = result[ which(result$dat_type == "emp"), "mean_p"], color = "red") + 
  facet_wrap(stdev ~ .) +
  ggtitle("Mean p") +
  theme_bw()
meanp_plot


```

```{r cleanup}
DBI::dbDisconnect(db)
```
