---
title: "ID gaps"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r stuff}
library(isds)
library(ggplot2)
library(dplyr)

source(here::here("analysis", "fxns2.r"))

portal_isd <- get_toy_portal_data(years = c(1980:1985), chosen_treatment = "control")
head(portal_isd)

raw_isd_plot <- ggplot(data = portal_isd, aes(x = wgt)) +
  geom_histogram(binwidth = 5) +
  theme_bw()

raw_isd_plot

portal_gmm <- fit_gmm(portal_isd)

portal_id <- integrate_gmm(portal_gmm)

portal_drops <- drops_wrapper(portal_isd, cutoffs = c(1, 5, 10)) %>%
  mutate(source = "empirical", sim = NA)

nsamples = 10

set.seed(1)
uniform_isds <- replicate(nsamples, expr = sample_uniform_isd(portal_isd), simplify = F)
constrained_isds <- replicate(nsamples, expr = sample_constrained_isd(portal_isd, size_relationship = "none"), simplify = F)
constrained_s_isds <- replicate(nsamples, expr = sample_constrained_isd(portal_isd, size_relationship = "negative"), simplify = F)

uniform_drops_summaries <- lapply(uniform_isds, FUN = drops_wrapper, cutoffs = c(1, 5, 10))
constrained_drops_summaries <- lapply(constrained_isds, FUN = drops_wrapper, cutoffs = c(1, 5, 10))
constrained_s_drops_summaries <- lapply(constrained_s_isds, FUN = drops_wrapper, cutoffs = c(1, 5, 10))

names(uniform_drops_summaries) <- 1:nsamples
names(constrained_drops_summaries) <- 1:nsamples
names(constrained_s_drops_summaries) <- 1:nsamples

uniform_drops_summaries <- dplyr::bind_rows(uniform_drops_summaries, .id = "sim")
uniform_drops_summaries$source = "uniform"
constrained_drops_summaries <- dplyr::bind_rows(constrained_drops_summaries, .id = "sim")
constrained_drops_summaries$source = "constrained"
constrained_s_drops_summaries <- dplyr::bind_rows(constrained_s_drops_summaries, .id = "sim")
constrained_s_drops_summaries$source = "constrained_s"

all_drop_summaries <- bind_rows(uniform_drops_summaries, constrained_drops_summaries, constrained_s_drops_summaries, portal_drops) %>%
  mutate(cutoff = as.factor(cutoff))

ndrops_plot <- ggplot(data = all_drop_summaries, aes(x = ndrops, fill = cutoff)) +
  geom_histogram(binwidth = 1) +
  theme_bw() +
  scale_fill_viridis_d(end = .8) +
  facet_grid(rows = vars(source), cols = vars(cutoff), switch = "y")

ndrops_plot
# 
# dropwidth_plot <-ggplot(data = all_drop_summaries, aes(x = mean_drop_width, fill = cutoff)) +
#   geom_histogram(binwidth = 5) +
#   theme_bw() +
#   scale_fill_viridis_d(end = .8) +
#   facet_grid(rows = vars(source), cols = vars(cutoff), switch = "y")
# 
# dropwidth_plot

npeaks_plot <- ggplot(data = distinct(select(all_drop_summaries, source, sim, npeaks)), aes(x = npeaks)) +
  geom_histogram(binwidth = 1) +
  theme_bw() +
  scale_fill_viridis_d(end = .8) +
  facet_grid(rows = vars(source), switch = "y")

npeaks_plot

```
