---
title: "KDEs, GMMs, and turns"
output: github_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)

knitr::opts_chunk$set(echo = TRUE)
all_kdes <- read.csv(here::here("all_kdes.csv"), stringsAsFactors = F)
all_isds <- read.csv(here::here("all_isds.csv"), stringsAsFactors = F) 
all_gmms <- read.csv(here::here("all_gmms.csv"), stringsAsFactors = F)

all_isds <- all_isds %>%
  mutate(sim = ifelse(is.na(sim), 1, sim))
all_gmms <- all_gmms %>%
  mutate(sim = ifelse(is.na(sim), 1, sim))
all_kdes <- all_kdes %>%
  mutate(sim = ifelse(is.na(sim), 1, sim))

```

```{r isd plots, fig.dim=c(20, 7)}

isd_plots <- ggplot(data = filter(all_isds, sim %in% c(NA, 1, 10, 20, 30, 40, 50, 60, 70, 80, 90)), aes(x = wgt)) +
  geom_density() +
  theme_bw() +
  facet_grid(cols = vars(sim), rows = vars(source), scales = "free_y", drop = T) +
  xlim(0, 300) +
  ggtitle("ISDs")
isd_plots
```


```{r kde plots, fig.dim=c(20, 7)}

kde_plots <- ggplot(data = filter(all_kdes, sim %in% c(NA, 1, 10, 20, 30, 40, 50, 60, 70, 80, 90)), aes(x = wgt, y = density)) +
  geom_point() +
  theme_bw() +
  facet_grid(cols = vars(sim), rows = vars(source), scales = "free_y", drop = T) +
  xlim(0, 300) +
  ggtitle("KDEs")
kde_plots
```


```{r gmm plots, fig.dim=c(20, 7)}

gmm_plots <- ggplot(data = filter(all_gmms, sim %in% c(NA, 1, 10, 20, 30, 40, 50, 60, 70, 80, 90)), aes(x = wgt, y = density)) +
  geom_point() +
  theme_bw() +
  facet_grid(cols = vars(sim), rows = vars(source), scales = "free_y", drop = T) +
  xlim(0, 300) +
  ggtitle("GMMss")
gmm_plots
```

```{r most density}

find_most_density <- function(density_vector, cutoff = .9) {
  
  density_df <- data.frame(initial_order = 1:length(density_vector),
                           density = density_vector)
  
  density_df <- density_df %>%
    arrange(desc(density)) %>%
    mutate(density_index = row_number())
  
  running_sum <- 0
  for(i in 1:nrow(density_df)) {
    running_sum <- running_sum + density_df$density[i]
    if(running_sum >= cutoff) {
      break
    }
  }
  
  density_df$in_most <- (density_df$density_index <= i)
  
  density_df <- density_df %>%
    arrange(initial_order)
  
  return(density_df$in_most)
}

all_gmms <- all_gmms %>%
  group_by(sim, source) %>%
  mutate(in_most = find_most_density(density, cutoff = .9)) %>%
  ungroup()

all_kdes <- all_kdes %>%
  group_by(sim, source) %>%
  mutate(in_most = find_most_density(density, cutoff = .9)) %>%
  ungroup()


```


```{r kde plots 2, fig.dim=c(20, 7)}

kde_plots <- ggplot(data = filter(all_kdes, sim %in% c(NA, 1, 10, 20, 30, 40, 50, 60, 70, 80, 90)), aes(x = wgt, y = density, color = in_most)) +
  geom_point() +
  theme_bw() +
  facet_grid(cols = vars(sim), rows = vars(source), scales = "free_y", drop = T) +
  xlim(0, 300) +
  ggtitle("KDEs")+
  scale_color_viridis_d(end = .6)
kde_plots
```


```{r gmm plots 2, fig.dim=c(20, 7)}

gmm_plots <- ggplot(data = filter(all_gmms, sim %in% c(NA, 1, 10, 20, 30, 40, 50, 60, 70, 80, 90)), aes(x = wgt, y = density, color = in_most)) +
  geom_point() +
  theme_bw() +
  facet_grid(cols = vars(sim), rows = vars(source), scales = "free_y", drop = T) +
  xlim(0, 300) +
  ggtitle("GMMs") +
  scale_color_viridis_d(end = .6)
gmm_plots
```


```{r numerical summaries}

all_kdes <- all_kdes %>%
  mutate(smoother = "kde") 
all_gmms <- all_gmms %>% 
  mutate(smoother = "gmm")

all <- bind_rows(all_kdes, all_gmms)


summarize_chunks <- function(in_most_df) {
  
  nchunks <- 0
  in_most_df$chunk <- NA
  
  for(i in 2:nrow(in_most_df)) {
    if(all(in_most_df$in_most[i], in_most_df$in_most[i - 1] == FALSE)) {
      nchunks <- nchunks + 1
    }
    
    if(all(nchunks > 0, in_most_df$in_most[i])) {
    in_most_df$chunk[i] <- nchunks
    }
  }
  
  min_in_most <- min(in_most_df[ which(in_most_df$in_most), "density"])
  max_in_most <- max(in_most_df[ which(in_most_df$in_most), "density"])
  
  edges_ratio <- max_in_most/min_in_most
  

  in_most_evenness <- in_most_df %>%
    filter(in_most) %>%
    group_by(chunk) %>%
    summarize(chunk_sum = sum(density)) %>%
    ungroup()
  
  chunk_dom <- vegan::diversity(in_most_evenness$chunk_sum, index = "simpson")
  
  
  
  output <- data.frame(sim = in_most_df$sim[1], source = in_most_df$source[1], smoother = in_most_df$smoother[1], nchunks = nchunks, edges_ratio = edges_ratio, chunk_dominance = chunk_dom, stringsAsFactors = F)
  
  return(output)
}
# 
# add_chunk <- function(in_most_df) {
#   
#   nchunks <- 0
#   in_most_df$chunk <- NA
#   
#   for(i in 2:nrow(in_most_df)) {
#     if(all(in_most_df$in_most[i], in_most_df$in_most[i - 1] == FALSE)) {
#       nchunks <- nchunks + 1
#     }
#     
#     if(nchunks > 0) {
#     in_most_df$chunk[i] <- nchunks
#     }
#   }
#   return(in_most_df)
# }

all_chunks <- list() 

for(i in 1:min(30, length(unique(all$sim)))) {
  for(j in 1:length(unique(all$smoother))) {
    for(k in 1:length(unique(all$source))) {
      this_df <- filter(all, sim == unique(all$sim)[i],
                        smoother == unique(all$smoother)[j],
                        source == unique(all$source)[k])
      if(nrow(this_df) < 1) {
        next
      }
      
      all_chunks[[length(all_chunks) + 1]] <- summarize_chunks(this_df)
    }
  }
}

all_chunks <- bind_rows(all_chunks)

all_chunks <- all_chunks %>%
  arrange(desc(nchunks)) %>%
  mutate(chunk_rank = row_number()) %>%
  arrange(desc(edges_ratio)) %>%
  mutate(edges_rank = row_number()) %>%
  group_by(smoother, nchunks) %>%
  arrange(desc(edges_ratio)) %>%
  mutate(within_nchunks_e_r = row_number()) %>%
  arrange(desc(chunk_dominance)) %>%
  mutate(dominance_rank = row_number()) %>%
  ungroup()


all <- left_join(all, all_chunks, by = c("sim", "smoother", "source")) %>%
  mutate(nchunks = as.factor(nchunks)) %>%
  group_by(sim, smoother, source) %>%
  mutate(p_sd = sd(density)) %>%
  ungroup()


```

```{r by nchunks plot}

nchunks_plot <- ggplot(data = filter(all, chunk_rank %% 10 == 1), aes(x = wgt, y = density, color = nchunks)) +
  geom_point(size = .5) +
  theme_bw() +
  scale_color_viridis_d(end = .8) +
  facet_wrap(vars(chunk_rank))

```


```{r by edge ratio plot alpha, fig.dim=c(40,20)}

gmm_er_plot <- ggplot(data =filter(all, smoother == "gmm", as.numeric(nchunks) > 1), aes(x = wgt, y = density, color = chunk_dominance, alpha = in_most)) +
  geom_point() +
  theme_bw() +
  scale_color_viridis_c(end = .8) +
  facet_grid(rows = vars(nchunks), cols = vars(dominance_rank), scales= "free") +
  ggtitle("GMMs")
gmm_er_plot


kde_er_plot <- ggplot(data =filter(all, smoother == "kde", as.numeric(nchunks) > 1), aes(x = wgt, y = density, color = chunk_dominance, alpha = in_most)) +
  geom_point() +
  theme_bw() +
  scale_color_viridis_c(end = .8) +
  facet_grid(rows = vars(nchunks), cols = vars(dominance_rank), scales= "free_x") +
  ggtitle("KDEs")
kde_er_plot

```
